/**
 * State Synchronization Layer
 * Automatically syncs state.json to derived views
 */

import * as path from 'path';
import { writeFile } from 'fs/promises';
import { ProjectState, TeamMember, AgentStatus } from './state-manager';

// ============================================================================
// Sync to Markdown Project File
// ============================================================================

/**
 * Sync state.json to {project-id}.md (human-readable project log)
 */
export async function syncToMarkdown(
  projectId: string,
  state: ProjectState,
  projectDir: string
): Promise<void> {
  const filepath = path.join(projectDir, `${projectId}.md`);
  const content = generateMarkdownContent(state);
  await writeFile(filepath, content, 'utf-8');
}

function generateMarkdownContent(state: ProjectState): string {
  return `# Project: ${state.id}

## Metadata

| Field | Value |
|-------|-------|
| **Project ID** | ${state.id} |
| **Status** | ${state.status} |
| **Mode** | ${state.mode} |
| **Created** | ${state.createdAt} |
| **Updated** | ${state.updatedAt} |

## User Request

${state.userRequest}

## Team

| Role | Agent ID | Status | Rework Count | Deliverable |
|------|----------|--------|--------------|-------------|
${state.team.map(m => `| ${m.role} | ${m.agentId} | ${m.status} | ${m.reworkCount} | ${m.deliverable || '-'} |`).join('\n')}

## Milestones

| Milestone | Status | User Confirmed | Timestamp |
|-----------|--------|----------------|-----------|
${state.milestones.map(m => `| ${m.name} | ${m.status} | ${m.userConfirmed !== undefined ? (m.userConfirmed ? '✅' : '⏳') : '-'} | ${m.timestamp || '-'} |`).join('\n')}

## Execution Log

| Timestamp | Phase | Event | Details |
|-----------|-------|-------|---------|
${state.logs.map(l => `| ${l.timestamp} | ${l.phase} | ${l.event} | ${l.details || '-'} |`).join('\n')}

## Disputes

${state.disputes.length === 0 ? 'No disputes recorded.' : state.disputes.map(d => `
### ${d.id}
- **Agents:** ${d.agents.join(', ')}
- **Topic:** ${d.topic}
- **Round:** ${d.round}
- **Resolution:** ${d.resolution || 'Pending'}
- **Timestamp:** ${d.timestamp}
`).join('\n')}

---

*This file is automatically generated and synchronized from state.json.*
`;
}

// ============================================================================
// Sync to Agent Status JSON
// ============================================================================

/**
 * Sync state.json to agent-status.json (real-time agent execution state)
 */
export async function syncToAgentStatus(
  projectId: string,
  state: ProjectState,
  projectDir: string
): Promise<void> {
  const filepath = path.join(projectDir, 'agent-status.json');

  // Extract agent status from state
  const agentStatusData = {
    projectId: state.id,
    lastUpdate: state.updatedAt,
    agents: state.agentStatus || {},
    teamMembers: state.team.map(member => ({
      role: member.role,
      agentId: member.agentId,
      status: member.status,
      deliverable: member.deliverable,
      reworkCount: member.reworkCount,
    })),
  };

  await writeFile(filepath, JSON.stringify(agentStatusData, null, 2), 'utf-8');
}

// ============================================================================
// Sync to Whiteboard Markdown
// ============================================================================

/**
 * Sync state.json to WHITEBOARD.md (team communication board)
 */
export async function syncToWhiteboard(
  projectId: string,
  state: ProjectState,
  projectDir: string
): Promise<void> {
  const filepath = path.join(projectDir, 'WHITEBOARD.md');
  const content = generateWhiteboardContent(state);
  await writeFile(filepath, content, 'utf-8');
}

function generateWhiteboardContent(state: ProjectState): string {
  const whiteboard = state.whiteboard || {
    teamMembers: [],
    currentPhase: 'init',
    blockers: [],
    decisions: [],
    lastUpdate: state.updatedAt,
  };

  return `# Team Whiteboard - ${state.id}

**Last Update:** ${whiteboard.lastUpdate}
**Current Phase:** ${whiteboard.currentPhase}

---

## 👥 Team Members

${whiteboard.teamMembers.length === 0 ? 'No team members yet.' : whiteboard.teamMembers.map(member =>
  `- **${member.role}** (${member.agentId}): ${member.status}`
).join('\n')}

---

## 🚧 Current Blockers

${whiteboard.blockers.length === 0 ? 'No blockers.' : whiteboard.blockers.map(blocker =>
  `- **${blocker.agentId}**: ${blocker.issue} _(${blocker.timestamp})_`
).join('\n')}

---

## 📋 Key Decisions

${whiteboard.decisions.length === 0 ? 'No decisions recorded yet.' : whiteboard.decisions.map(decision =>
  `- **${decision.topic}**: ${decision.decision} _(${decision.timestamp})_`
).join('\n')}

---

## 📊 Agent Status Details

${state.agentStatus && Object.keys(state.agentStatus).length > 0 ?
  Object.values(state.agentStatus).map(agent => `
### ${agent.role} (${agent.agentId})
- **State:** ${agent.state}
- **Phase:** ${agent.phase}
- **Progress:** ${agent.progress}%
- **Last Update:** ${agent.lastUpdate}
${agent.restartCount ? `- **Restart Count:** ${agent.restartCount}` : ''}
${agent.timeoutHistory && agent.timeoutHistory.length > 0 ? `- **Timeout History:** ${agent.timeoutHistory.length} timeout(s)` : ''}
`).join('\n') : 'No agent status details available.'}

---

*This whiteboard is automatically synchronized from state.json.*
`;
}

// ============================================================================
// Sync All Derived Views
// ============================================================================

/**
 * Sync state.json to all derived views
 */
export async function syncAll(
  projectId: string,
  state: ProjectState,
  projectDir: string
): Promise<void> {
  await Promise.all([
    syncToMarkdown(projectId, state, projectDir),
    syncToAgentStatus(projectId, state, projectDir),
    syncToWhiteboard(projectId, state, projectDir),
  ]);
}
